name: Test1

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: early print
      run: |
        pwd
        ls
    - name: So build
      run: |
        chmod +x ./build.sh
        sudo ./build.sh
    - name: test
      run: |
        pwd
        ls
        env
