name: Test1

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: early print
      run: |
        pwd
        ls
    - name: Downloading
      run: |
        chmod +x ./fetch.sh
        sudo ./fetch.sh
    - name: Building
      run: |
        chmod +x ./build.sh
        sudo ./build.sh
    - uses: actions/upload-artifact@v1
      with:
        name: engine-linux-x64
        path: engine_out
    - name: test
      run: |
        pwd
        ls
        env
