name: Flutter Engine

on: [push]

jobs:
  linux:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        config:
        - gn: --embedder-for-target --runtime-mode=debug --unoptimized --android
          tag: android_debug_unopt
        - gn: --embedder-for-target --runtime-mode=debug --unoptimized --android --android-cpu=arm64
          tag: android_debug_unopt_arm64
    steps:
    - uses: actions/checkout@v1
    - name: Download
      run: ./linux-download.sh
    - name: Patch
      run: |
        cp main.gn engine/src/flutter/BUILD.gn
        cp embedder.gn engine/src/flutter/shell/platform/embedder/BUILD.gn
        cp embedder_exports.lst engine/src/flutter/shell/platform/embedder/embedder_exports.lst
    - name: Dart
      run: ./linux-dart.sh
    - name: Generate configs
      run: ${{ format('./linux-gn.sh \"{0}\"', matrix.gn) }}
    - name: Build
      run: ${{ format('./linux-build.sh {0}', matrix.tag) }}
    - name: Print tree
      run: tree engine/src/out
    - name: Uploading artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ format('engine-linux_x64-{0}', matrix.tag) }}
        path: engine_out
  
  linux-icu:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Download
      run: ./linux-download.sh
    - name: Build icudtl
      run: ./linux-icu.sh
    - name: Uploading artifacts
      uses: actions/upload-artifact@v1
      with:
        name: engine-linux_x64-icudtl
        path: engine_out