name: Flutter Engine

on: [push]

jobs:
  linux:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        config:
        - tag: android_debug_unopt
          gn: --embedder-for-target --runtime-mode=debug --unoptimized --android
        - tag: android_debug_unopt_arm64
          gn: --embedder-for-target --runtime-mode=debug --unoptimized --android --android-cpu=arm64
        - tag: android_debug_unopt_x86
          gn: --embedder-for-target --runtime-mode=debug --unoptimized --android --android-cpu=x86
        - tag: android_debug_unopt_x64
          gn: --embedder-for-target --runtime-mode=debug --unoptimized --android --android-cpu=x64
        - tag: host_debug_unopt
          gn: --embedder-for-target --runtime-mode=debug --unoptimized

        - tag: android_profile
          gn: --embedder-for-target --runtime-mode profile --lto --android
        - tag: android_profile_arm64
          gn: --embedder-for-target --runtime-mode profile --lto --android --android-cpu=arm64
        - tag: android_profile_x86
          gn: --embedder-for-target --runtime-mode profile --lto --android --android-cpu=x86
        - tag: android_profile_x64
          gn: --embedder-for-target --runtime-mode profile --lto --android --android-cpu=x64
        - tag: host_profile
          gn: --embedder-for-target --runtime-mode profile --lto

        - tag: android_release
          gn: --embedder-for-target --runtime-mode release --lto --stripped --android
        - tag: android_release_arm64
          gn: --embedder-for-target --runtime-mode release --lto --stripped --android --android-cpu=arm64
        - tag: android_release_x86
          gn: --embedder-for-target --runtime-mode release --lto --stripped --android --android-cpu=x86
        - tag: android_release_x64
          gn: --embedder-for-target --runtime-mode release --lto --stripped --android --android-cpu=x64
        - tag: host_release
          gn: --embedder-for-target --runtime-mode release --lto --stripped
    steps:
    - uses: actions/checkout@v1
    - name: Download
      run: ./linux-download.sh
    - name: Patch
      run: |
        cp main.gn engine/src/flutter/BUILD.gn
        cp embedder.gn engine/src/flutter/shell/platform/embedder/BUILD.gn
        cp embedder_exports.lst engine/src/flutter/shell/platform/embedder/embedder_exports.lst
    - name: Dart
      run: ./linux-dart.sh
    - name: Generate configs
      run: ${{ format('./linux-gn.sh "{0}"', matrix.config.gn) }}
    - name: Build
      run: ${{ format('./linux-build.sh {0}', matrix.config.tag) }}
    - name: Print tree
      run: tree engine/src/out
    - name: Uploading artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ format('engine-linux_x64-{0}', matrix.config.tag) }}
        path: engine_out