name: Flutter Engine

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1

    - name: Fix permissions
      run: |
        chmod +x ./linux-download.sh
        chmod +x ./linux-build.sh
        chmod +x ./linux-icu.sh

    - name: Download
      run: ./linux-download.sh

    - name: Generate configs
      working-directory: engine/src
      run: |
        ./flutter/tools/gn --runtime-mode=debug --unoptimized --android
        ./flutter/tools/gn --runtime-mode=debug --unoptimized --android --android-cpu=arm64
        ./flutter/tools/gn --runtime-mode=debug --unoptimized --android --android-cpu=x86
        ./flutter/tools/gn --runtime-mode=debug --unoptimized --android --android-cpu=x64
        ./flutter/tools/gn --runtime-mode=debug --unoptimized

        ./flutter/tools/gn --runtime-mode profile --lto --android
        ./flutter/tools/gn --runtime-mode profile --lto --android --android-cpu=arm64
        ./flutter/tools/gn --runtime-mode profile --lto --android --android-cpu=x86
        ./flutter/tools/gn --runtime-mode profile --lto --android --android-cpu=x64
        ./flutter/tools/gn --runtime-mode profile --lto

        ./flutter/tools/gn --runtime-mode release --lto --stripped --android
        ./flutter/tools/gn --runtime-mode release --lto --stripped --android --android-cpu=arm64
        ./flutter/tools/gn --runtime-mode release --lto --stripped --android --android-cpu=x86
        ./flutter/tools/gn --runtime-mode release --lto --stripped --android --android-cpu=x64
        ./flutter/tools/gn --runtime-mode release --lto --stripped

    - name: Build android_debug_unopt
      run: ./linux-build.sh android_debug_unopt
    - name: Build android_debug_unopt_arm64
      run: ./linux-build.sh android_debug_unopt_arm64
    - name: Build android_debug_unopt_x86
      run: ./linux-build.sh android_debug_unopt_x86
    - name: Build android_debug_unopt_x64
      run: ./linux-build.sh android_debug_unopt_x64
    - name: Build host_debug_unopt
      run: ./linux-build.sh host_debug_unopt

    - name: Build android_profile
      run: ./linux-build.sh android_profile
    - name: Build android_profile_arm64
      run: ./linux-build.sh android_profile_arm64
    - name: Build android_profile_x86
      run: ./linux-build.sh android_profile_x86
    - name: Build android_profile_x64
      run: ./linux-build.sh android_profile_x64
    - name: Build host_profile
      run: ./linux-build.sh host_profile

    - name: Build android_release
      run: ./linux-build.sh android_release
    - name: Build android_release_arm64
      run: ./linux-build.sh android_release_arm64
    - name: Build android_release_x86
      run: ./linux-build.sh android_release_x86
    - name: Build android_release_x64
      run: ./linux-build.sh android_release_x64
    - name: Build host_release
      run: ./linux-build.sh host_release

    - name: Build icudtl
      run: ./linux-icu.sh

    - name: Uploading artifacts
      uses: actions/upload-artifact@v1
      with:
        name: engine-linux-x64
        path: engine_out
