name: Test1

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    env:
      DEPOT_TOOLS_PATH: depot_tools
      BUILDROOT_PATH: buildroot
      ENGINE_PATH: engine
    steps:
    - uses: actions/checkout@v1
    - name: early print
      run: |
        pwd
        ls
    - name: test sudo
      run: |
        chmod +x ./build.sh
        sudo ./build.sh
    - name: test
      run: |
        pwd
        ls
